# Generated by Django 5.2.4 on 2025-07-14 04:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BogieForm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('formNumber', models.CharField(max_length=50)),
                ('insepctionBy', models.CharField(max_length=100)),
                ('insepctionDate', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='WheelForm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('formNumber', models.CharField(max_length=50)),
                ('submittedBy', models.CharField(max_length=100)),
                ('submittedDate', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='BogieDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bogieNo', models.CharField(max_length=50)),
                ('dateOfIOH', models.DateField()),
                ('deficitComponents', models.CharField(max_length=255)),
                ('incomingDivAndDate', models.CharField(max_length=100)),
                ('makerYearBuilt', models.CharField(max_length=100)),
                ('form', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='bogieDetails', to='forms.bogieform')),
            ],
        ),
        migrations.CreateModel(
            name='BogieChecksheet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('axleGuide', models.CharField(max_length=50)),
                ('bogieFrameCondition', models.CharField(max_length=50)),
                ('bolster', models.CharField(max_length=50)),
                ('bolsterSuspensionBracket', models.CharField(max_length=50)),
                ('lowerSpringSeat', models.CharField(max_length=50)),
                ('form', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='bogieChecksheet', to='forms.bogieform')),
            ],
        ),
        migrations.CreateModel(
            name='BMBCChecksheet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('adjustingTube', models.CharField(max_length=50)),
                ('cylinderBody', models.CharField(max_length=50)),
                ('pistonTrunnion', models.CharField(max_length=50)),
                ('plungerSpring', models.CharField(max_length=50)),
                ('form', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='bmbcChecksheet', to='forms.bogieform')),
            ],
        ),
        migrations.CreateModel(
            name='WheelFields',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('treadDiameterNew', models.CharField(max_length=50)),
                ('lastShopIssueSize', models.CharField(max_length=50)),
                ('condemningDia', models.CharField(max_length=50)),
                ('wheelGauge', models.CharField(max_length=50)),
                ('variationSameAxle', models.CharField(max_length=50)),
                ('variationSameBogie', models.CharField(max_length=50)),
                ('variationSameCoach', models.CharField(max_length=50)),
                ('wheelProfile', models.CharField(max_length=100)),
                ('intermediateWWP', models.CharField(max_length=100)),
                ('bearingSeatDiameter', models.CharField(max_length=100)),
                ('rollerBearingOuterDia', models.CharField(max_length=100)),
                ('rollerBearingBoreDia', models.CharField(max_length=100)),
                ('rollerBearingWidth', models.CharField(max_length=100)),
                ('axleBoxHousingBoreDia', models.CharField(max_length=100)),
                ('wheelDiscWidth', models.CharField(max_length=100)),
                ('form', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='fields', to='forms.wheelform')),
            ],
        ),
    ]
