# Generated by Django 5.2.4 on 2025-07-14 08:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bogieform',
            old_name='insepctionBy',
            new_name='insepction_by',
        ),
        migrations.RenameField(
            model_name='bogieform',
            old_name='insepctionDate',
            new_name='insepction_date',
        ),
    ]
