# Generated by Django 5.2.4 on 2025-07-14 08:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0002_rename_insepctionby_bogieform_insepction_by_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bogieform',
            old_name='insepction_by',
            new_name='inspection_by',
        ),
        migrations.RenameField(
            model_name='bogieform',
            old_name='insepction_date',
            new_name='inspection_date',
        ),
    ]
